# NumPy Core Concepts & Operations
  This notebook covers core NumPy operations used in data processing and machine learning.

  Tools : Python, NumPy

In [1]:
import numpy as np

# Create NumPy Arrays from lists


In [5]:
#create NumPy Arrays from lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

arr2= np.array([1,2,3,4,5,"prime"])
print(arr2, type(arr2), arr2.dtype)

arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D, arr2D.shape)


[1 2 3 4 5] <class 'numpy.ndarray'>
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [23]:
#create
arr1 = np.zeros((2,3), dtype = "int64") #prefill
print(arr1, arr1.shape)

arr2 = np.ones((5,), dtype = "int64") #prefill
print(arr2, arr2.shape)

arr3 = np.full((3,4),100) #prefill with val
print(arr3, arr3.shape)

arr4= np.eye(3)  #identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(1,10,2) #range elements start,end,step
print(arr5, arr5.shape)

arr6 = np.linspace(1,100,4) #evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1 1 1 1 1] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)


# Array Attributes

In [30]:
#properties
arr = np.array([[1,2,3],[4,5,6,],[7,8,9]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)


(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


# Reshaping Arrays


In [34]:
#Operations on arrays

arr = np.array([[1,2,3], [4,5,6]])
print(arr,arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped,reshaped.shape)

flattened = arr.flatten() #2D => 1D
print(flattened,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


# Indexing And Slicing

In [38]:
#Indexing
#arr = np.array([1,2,3,4,5])
arr = np.array([[1,2,3], [4,5,6]])

print(arr[0,2])

3


In [40]:
#fancy Indexing
arr = np.array([1,2,3,4,5])
idx = [0,1,3]
print(arr[idx])

[1 2 4]


In [41]:
#boolean indexing
arr = np.array([1,2,3,4,5])
print(arr[arr>2])

[3 4 5]


In [44]:
#slicing
arr = np.array([1,2,3,4,5])
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])


[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [51]:
#copy vs View
nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200
print(sub_list)
print(nums)

arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
print(sub_arr)

sub_arr[0] = 200
print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]


# Data Types


In [59]:
#data types
arr1 = np.array([1,2,3,4,5]) #int
print(arr1,arr1.dtype)
arr = np.array([1,2,3.14,4,5])#float
print(arr,arr.dtype)

arr2 = np.array([1,2,3.14,4,5,"prime"]) 
print(arr2,arr2.dtype)

arr3 = np.array([3 +5j]) #complex
print(arr3,arr3.dtype)

arr4= np.array([1,{2,3.14,4},5,"prime"]) #object
print(arr4,arr4.dtype)



[1 2 3 4 5] int64
[1.   2.   3.14 4.   5.  ] float64
['1' '2' '3.14' '4' '5' 'prime'] <U32
[3.+5.j] complex128
[1 {2, 3.14, 4} 5 'prime'] object


# 2D Array


In [64]:
#2D Arrays

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


# 3D Array


In [69]:
#3D array

arr3D = np.array([[[1,2],[3,4],[5,6]], [[7,8],[9,10],[11,12]]]) #2*3*2

print(arr3D, arr3D.shape)

#Indexing
print(arr3D[0,1,1])

#slicing
print(arr3D[:,0,:]) # FIRST ROW FROM BOTH LAYERS
print(arr3D[:,:,0]) # FIRST column FROM BOTH LAYERS



[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


# Vectorization



In [71]:
# vectorization

arr = np.array([1,2,3,4,5])

print(arr **2)
print(arr + 10)

[ 1  4  9 16 25]
[11 12 13 14 15]


# Broadcasting


In [73]:
#broadcasting
arr = np.array([1,2,3,4,5])
arr2= np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(arr.shape)
print(arr2.shape)


(5,)
(2, 5)


# Normalization

In [78]:
#normalize

arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)
print(mean)
print(std_dev)
print(np.sqrt(5/4))

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
1.118033988749895


# Aggregation

In [84]:
# mathematical functions
#aggregation

arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0
